# Package metadata
PACKAGE=iio-oscilloscope
ARCHITECTURE=armhf
DEPENDS="libfuse2t64, libxcb-icccm4, libxcb-image0, libxcb-keysyms1, libxcb-render-util0, libxcb-xinerama0, libxkbcommon-x11-0, libxcb-xkb1, libmatio13"
MAINTAINER="Engineerzone <https://ez.analog.com/sw-interface-tools>"
HOMEPAGE="https://github.com/analogdevicesinc/iio-oscilloscope"
DESCRIPTION="IIO Oscilloscope for ARMHF architecture"
LONG_DESCRIPTION="This package contains the IIO Oscilloscope software from Analog Devices for ARMHF architecture."

