image: Ubuntu1804

build: off
test: off

init:
  - sudo apt update
  - sudo apt -y install git cmake gcc-mingw-w64 pkg-config libgtk2.0-dev xvfb

install:
  - Xvfb :0 -screen 0 1024x768x16 &
  - sudo apt -y install wine64
  - appveyor DownloadFile http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe innosetup-5.6.1.exe
  - DISPLAY=:0.0 wine innosetup-5.6.1.exe \/VERYSILENT \/SUPPRESSMSGBOXES

  - 'appveyor DownloadFile "https://ci.appveyor.com/api/projects/analogdevicesinc/iio-osc-mingw/artifacts/iio-osc-i686-build-deps.tar.xz?branch=master&job=Environment: MINGW_VERSION=i686" -FileName iio-osc-i686-build-deps.tar.xz'
  - 'appveyor DownloadFile "https://ci.appveyor.com/api/projects/analogdevicesinc/iio-osc-mingw/artifacts/iio-osc-x86_64-build-deps.tar.xz?branch=master&job=Environment: MINGW_VERSION=x86_64" -FileName iio-osc-x86_64-build-deps.tar.xz'

  - tar -xf iio-osc-i686-build-deps.tar.xz
  - tar -xf iio-osc-x86_64-build-deps.tar.xz

build_script:
  - CI/appveyor/build.sh i686
  - CI/appveyor/build.sh x86_64

after_build:
  - export OSC_BUILD_VER=`git describe --tags --always HEAD`
  - sed "s/UNSET_VERSION/${OSC_BUILD_VER}/" osc.iss > updated-osc.iss

  - wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Inno\ Setup\ 5/ISCC.exe updated-osc.iss
  - appveyor PushArtifact adi-osc-setup.exe

