variables:
  libiioPipelineId: 9
  libad9361iioPipelineId: 10

trigger:
- main
- master
- staging/*
- 20*

pr:
- main
- master
- 20*

jobs:
- job: LinuxBuilds
  strategy:
    matrix:
      centos_8_x86_64:
        imageName: 'ubuntu-latest'
        OS_TYPE: 'centos_docker'
        OS_VERSION: centos8
        artifactName: 'Linux-CentOS-8-x86_64'
        PACKAGE_TO_INSTALL: 'build/*.rpm'
      ubuntu_20_04_x86_64:
        imageName: 'ubuntu-latest'
        OS_TYPE: 'ubuntu_docker'
        OS_VERSION: focal
        artifactName: 'Linux-Ubuntu-20.04-x86_64'
        PACKAGE_TO_INSTALL: 'build/*.deb'
      debian_buster_arm32v7:
        imageName: 'ubuntu-latest'
        OS_TYPE: 'arm32v7/debian_docker'
        OS_VERSION: 'buster'
        artifactName: 'Linux-Debian-Buster-ARM'
        PACKAGE_TO_INSTALL: 'build/*.deb'
      debian_buster_arm64v8:
        imageName: 'ubuntu-latest'
        OS_TYPE: 'arm64v8/debian_docker'
        OS_VERSION: 'buster'
        artifactName: 'Linux-Debian-Buster-ARM64'
        PACKAGE_TO_INSTALL: 'build/*.deb'
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    name: 'Get libiio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    name: 'Get libad9361-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9361iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: ./CI/travis/before_install_linux
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_linux
    displayName: "Build"

- job: macOSBuilds
  strategy:
    matrix:
      macOS_10_15:
        imageName: 'macOS-10.15'
        artifactName: 'macOS-10.15'
  pool:
    vmImage: $(imageName)
  variables:
    PACKAGE_TO_INSTALL: 'build/*.pkg'
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    name: 'Get libiio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    name: 'Get libad9361-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9361iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - script: ./CI/travis/before_install_darwin
    displayName: "Install Dependencies"
  - script: ./CI/travis/make_darwin
    displayName: "Build"

- job: WindowsBuilds
  strategy:
    matrix:
      VS2019_Win32:
        imageName: 'windows-2019'
        COMPILER: 'Visual Studio 16 2019'
        ARCH: 'Win32'
        artifactName: 'Windows-VS-16-2019-Win32'
      VS2019_Win64:
        imageName: 'windows-2019'
        COMPILER: 'Visual Studio 16 2019'
        ARCH: 'x64'
        artifactName: 'Windows-VS-16-2019-x64'
  pool:
    vmImage: $[ variables['imageName'] ]
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true
  - task: DownloadPipelineArtifact@2
    name: 'Get libiio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libiioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: DownloadPipelineArtifact@2
    name: 'Get libad9361-iio artifacts'
    inputs:
      source: 'specific'
      project: '$(System.TeamProjectId)'
      pipeline: $(libad9361iioPipelineId)
      artifact: '$(artifactName)'
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Agent.BuildDirectory)/s/build/'
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: .\CI\install_deps_win.ps1
    displayName: Dependencies
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: .\CI\build_win.ps1
    displayName: Build
