variables:
  libiioPipelineId: 9
  libad9361iioPipelineId: 10
  libad9166iioPipelineId: 41

trigger:
  branches:
    include:
    - main
    - master
    - staging/*
    - 20*
  tags:
    include:
    - v*

pr:
  branches:
    include:
    - main
    - master
    - 20*

stages:
- stage: Builds
  #############################################
  # Builds
  #############################################
  jobs:
  - job: LinuxBuilds
    strategy:
      matrix:
        ubuntu_20_04_x86_64:
          imageName: 'ubuntu-20.04'
          OS_TYPE: 'ubuntu_docker'
          OS_VERSION: focal
          artifactName: 'Linux-Ubuntu-20.04'
          PACKAGE_TO_INSTALL: 'download/*.deb'
        ubuntu_22_04_x86_64:
          imageName: 'ubuntu-22.04'
          OS_TYPE: 'ubuntu_docker'
          OS_VERSION: jammy
          artifactName: 'Linux-Ubuntu-22.04'
          PACKAGE_TO_INSTALL: 'download/*.deb'
    pool:
      vmImage: $(imageName)
    steps:
    - checkout: self
      fetchDepth: 1
      clean: true
      persistCredentials: true
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: '$(System.TeamProjectId)'
        pipeline: $(libiioPipelineId)
        artifact: '$(artifactName)'
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/libiio-v0'
        path: '$(Agent.BuildDirectory)/s/download/'
      displayName: 'Get libiio artifacts'
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: '$(System.TeamProjectId)'
        pipeline: $(libad9361iioPipelineId)
        artifact: '$(artifactName)'
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/libad9361-iio-v0'
        path: '$(Agent.BuildDirectory)/s/download/'
      displayName: 'Get libad9361-iio artifacts'
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: '$(System.TeamProjectId)'
        pipeline: $(libad9166iioPipelineId)
        artifact: '$(artifactName)'
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/libad9166-iio-v0'
        path: '$(Agent.BuildDirectory)/s/download/'
      displayName: 'Get libad9166-iio artifacts'
    - script: |
        ./CI/azure/build_osc_ubuntu.sh install_apt_pkgs
        ./CI/azure/build_osc_ubuntu.sh install_adi_debs
        ./CI/azure/build_osc_ubuntu.sh install_gtkdatabox
      displayName: 'Install Dependencies'
    - script: |
        ./CI/azure/build_osc_ubuntu.sh build_osc
      displayName: "Build"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: '$(artifactName)'

  #######################################

  - job: ARMBuilds
    # Host Box
    pool:
      vmImage: "ubuntu-latest"
    # Docker Images
    strategy:
      matrix:
        ubuntu-ppc64le:
          image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
          arch: ppc64le
          artifactName: 'Ubuntu-ppc64le'
        ubuntu-x390x:
          image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
          arch: s390x
          artifactName: 'Ubuntu-x390x'
        debian_buster_arm32v7:
          image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
          arch: arm
          artifactName: 'Ubuntu-arm32v7'
        debian_buster_arm64v8:
          image: tfcollins/libiio_ubuntu_18_04-ci-arm-ppc:latest
          arch: aarch64
          artifactName: 'Ubuntu-arm64v8'
    steps:
    - checkout: self
      fetchDepth: 1
      clean: true
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: '$(System.TeamProjectId)'
        pipeline: $(libiioPipelineId)
        artifact: '$(artifactName)'
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/libiio-v0'
        path: '$(Agent.BuildDirectory)/s/download/'
      displayName: 'Get libiio artifacts'
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: '$(System.TeamProjectId)'
        pipeline: $(libad9361iioPipelineId)
        artifact: '$(artifactName)'
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/libad9361-iio-v0'
        path: '$(Agent.BuildDirectory)/s/download/'
      displayName: 'Get libad9361-iio artifacts'
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: '$(System.TeamProjectId)'
        pipeline: $(libad9166iioPipelineId)
        artifact: '$(artifactName)'
        runVersion: 'latestFromBranch'
        runBranch: 'refs/heads/libad9166-iio-v0'
        path: '$(Agent.BuildDirectory)/s/download/'
      displayName: 'Get libad9166-iio artifacts'
    - script: |
        set -e
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt-get install -y g++-arm-linux-gnueabihf
        sudo apt-get install -y g++-aarch64-linux-gnu
        sudo apt-get install -y qemu-system-ppc64
        sudo apt-get install qemu binfmt-support qemu-user-static
        sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      displayName: "Setup"
    - script: |
        set -e
        sudo docker run -m=4g --name iio-oscilloscope --platform "linux/$(arch)" -e ARTIFACTNAME=$(artifactName) -v "$(Agent.BuildDirectory)/s":"/ci" -v "/usr/bin/qemu-$(arch)-static":"/usr/bin/qemu-$(arch)-static" "$(image)" /bin/bash -c "cd /ci/ && chmod +x ./CI/azure/build_osc_arm.sh && ./CI/azure/build_osc_arm.sh install_apt_pkgs && ./CI/azure/build_osc_arm.sh install_gtkdatabox && ./CI/azure/build_osc_arm.sh install_adi_debs && ./CI/azure/build_osc_arm.sh build_osc"
        sudo docker ps -a
      displayName: "Install dependencies + build"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: '$(artifactName)'

  #########################################
        # !!! Uncomment macOSBuilds when will be added fixes on development side !!!

        #- job: macOSBuilds
        #strategy:
        #matrix:
        #macOS_11:
        #imageName: 'macOS-11'
        #artifactName: 'macOS-11'
        #macOS_12:
        #imageName: 'macOS-12'
        #artifactName: 'macOS-12'
        #pool:
        #vmImage: $(imageName)
        #steps:
        #- checkout: self
        #fetchDepth: 1
        #clean: true
        #- task: DownloadPipelineArtifact@2
        #inputs:
        #source: 'specific'
        #project: '$(System.TeamProjectId)'
        #pipeline: $(libad9361iioPipelineId)
        #artifact: '$(artifactName)'
        #runVersion: 'latestFromBranch'
        #runBranch: 'refs/heads/master'
        #path: '$(Agent.BuildDirectory)/s/download/'
        #displayName: 'Get libad9361-iio artifacts'
        #- task: DownloadPipelineArtifact@2
        #inputs:
        #source: 'specific'
        #project: '$(System.TeamProjectId)'
        #pipeline: $(libad9166iioPipelineId)
        #artifact: '$(artifactName)'
        #runVersion: 'latestFromBranch'
        #runBranch: 'refs/heads/master'
        #path: '$(Agent.BuildDirectory)/s/download/'
        #displayName: 'Get libad9166-iio artifacts'
        #- script: |
        #echo ${CMAKE_CXX_COMPILER_VERSION}
        #./CI/azure/build_osc_darwin.sh install_deps
        #./CI/azure/build_osc_darwin.sh install_adi_pkgs
        #displayName: "Install Dependencies"
        #- script: ./CI/azure/build_osc_darwin.sh build_osc
        #displayName: "Build"
        #- task: PublishPipelineArtifact@1
        #condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        #inputs:
        #targetPath: '$(Build.ArtifactStagingDirectory)'
        #artifactName: '$(artifactName)'
