#!/bin/sh -e

. CI/travis/lib.sh
. CI/travis/before_install_lib.sh

brew_install_if_not_exists cmake fftw libmatio \
	libxml2 pkg-config libusb gtk+ gtkdatabox \
	jansson glib curl openssl@1.1 \
	gettext libserialport python


