#!/bin/bash
set -e

source ./CI/travis/lib.sh
source ./CI/travis/before_install_lib.sh

sudo apt-get -qq update
sudo apt-get install -y build-essential libxml2-dev libcurl4-openssl-dev \
	libmatio-dev libglib2.0-dev libfftw3-dev libusb-dev libjansson-dev \
	cmake libgtk2.0-dev libgtkdatabox-dev bison flex doxygen

if [ "$TRAVIS" == "true" ] ; then
	for pkg in libiio libad9361-iio ; do
		wget http://swdownloads.analog.com/cse/travis_builds/master_latest_${pkg}${LDIST}.deb
		sudo dpkg -i ./master_latest_${pkg}${LDIST}.deb
	done
else
	cmake_build_git "libiio" "https://github.com/analogdevicesinc/libiio" "" "-DINSTALL_UDEV_RULE:BOOL=OFF"

	cmake_build_git "libad9361-iio" "https://github.com/analogdevicesinc/libad9361-iio" "" "-DLIBIIO_INCLUDEDIR:PATH=$STAGINGDIR/include -DLIBIIO_LIBRARIES:FILEPATH=$STAGINGDIR/lib/libiio.so"
fi

