#!/bin/sh -e

. CI/travis/lib.sh
. CI/travis/before_install_lib.sh

# handle_centos() {

# 	# First EPEL stuff
# 	yum install -y epel-release yum-utils
# 	yum config-manager --set-enabled powertools

# 	# FIXME: see about adding `libserialport-dev` from EPEL ; maybe libusb-1.0.0-devel...
# 	yum -y groupinstall 'Development Tools'
	
# 	yum -y install wget
# 	wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
# 	tar -zxvf cmake-3.15.2.tar.gz
# 	cd cmake-3.15.2
# 	./bootstrap
# 	make
# 	make install
# 	cd ..
# 	yum -y install epel-release
# 	yum -y install libzstd

# 	yum -y install dnf
# 	dnf -y --enablerepo=powertools install doxygen
	
# 	yum -y install  libxml2-devel libcurl-devel glib2-devel \
#                fftw-devel libusb1-devel jansson-devel cmake gtk2-devel \
#                bison flex matio-devel libaio-devel libtool avahi-devel


# 	# XXX: There is no gtkdatabox available in CentOS or EPEL....
# 	make_build_wget "gtkdatabox-0.9.3.0" "https://sourceforge.net/projects/gtkdatabox/files/gtkdatabox/0.9.3.0/gtkdatabox-0.9.3.0.tar.gz/download"
# }

handle_default() {
	sudo apt-get -qq update
	sudo DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libxml2-dev \
		libcurl4-openssl-dev libmatio-dev libglib2.0-dev libfftw3-dev libusb-1.0-0-dev \
		libjansson-dev cmake libgtk2.0-dev libgtkdatabox-dev bison flex doxygen \
		libaio-dev libavahi-client-dev libserialport-dev
}

handle_ubuntu() {
	handle_default
}

handle_debian() {
	handle_default
}

setup_build_type_env_vars

handle_${BUILD_TYPE}
