#!/bin/bash
set -e

source ./CI/travis/lib.sh

if command -v brew ; then
	QT_PATH="$(brew --prefix qt)/bin"
	export PATH="${QT_PATH}:$PATH"
fi

mkdir -p build

pushd build

if [ "$TRAVIS" == "true" ] ; then
	cmake ..
	make -j${NUM_JOBS}
else
	PKG_CONFIG_PATH="$STAGINGDIR/lib/pkgconfig" \
	cmake -DCMAKE_PREFIX_PATH="$STAGINGDIR" -DCMAKE_INSTALL_PREFIX="$STAGINGDIR" \
		-DCMAKE_EXE_LINKER_FLAGS="-L${STAGINGDIR}/lib" ..
	CFLAGS=-I${STAGINGDIR}/include LDFLAGS=-L${STAGINGDIR}/lib make -j${NUM_JOBS}
fi

popd
