name: windows-mingw build

on: [push, pull_request]

jobs:

  make-exe-64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull the Docker Image
      run: docker pull shooteu/iio-oscilloscope 
      
    - name: Run Docker Image
      shell: cmd
      run: |
            mkdir %GITHUB_WORKSPACE%\artifacts & echo %GITHUB_WORKSPACE%

            set "BUILD_HOST=windows-2019"
            set "USERNAME=github-actions"
            for /F %%a in ('git describe --tags --always HEAD') do set "TAG=%%a"
            for /F "tokens=1,2 delims=/" %%a in ("%GITHUB_REPOSITORY%") do (
              set "GITHUB_REPO_OWNER=%%a"
              set "GITHUB_REPO_NAME=%%b"
            )

            echo %BUILD_HOST% & echo %USERNAME% & echo %GITHUB_REPO_OWNER% & echo %GITHUB_REPO_NAME%
            echo %cd%
            docker run ^
                -v %cd%:C:\msys64\home\docker\iio-oscilloscope:rw ^
                -v %GITHUB_WORKSPACE%\artifacts:C:\msys64\home\docker\artifact:rw ^
                -e BRANCH=%GITHUB_REF_NAME% ^
                -e HEAD_BRANCH=%GITHUB_HEAD_REF% ^
                -e OSC_BUILD_VER=%TAG% ^
                -e LIBIIO_BRANCH=v0.24 ^
                -e LIBAD9361_BRANCH=master ^
                -e LIBAD9166_BRANCH=master ^
                shooteu/iio-oscilloscope C:\msys64\usr\bin\bash.exe -c '/home/docker/iio-oscilloscope/CI/docker/inside_docker.sh'
            
    - uses: actions/upload-artifact@v3
      with:
        name: adi-osc-setup
        path: ${{ github.workspace }}\artifacts\adi-osc-setup.exe
