name: Build ARM AppImage and Debian packages

on: [push, pull_request]

permissions:
  contents: read

env:
  APP_NAME: iio-oscilloscope

jobs:
  build_debian_package:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: arm64v8/debian:trixie
            distro: debian13
            architecture: aarch64
            platform_flag: ""
          - docker_image: arm32v7/debian:trixie
            distro: debian13
            architecture: armhf
            platform_flag: "--platform linux/arm/v7"

    steps:
      - uses: actions/checkout@v6
        with:
          path: ${{env.APP_NAME}}

      - name: Start persistent container
        run: |
          docker run -d \
              ${{matrix.platform_flag}} \
              --name ${{matrix.distro}}-${{matrix.architecture}} \
              -v "$GITHUB_WORKSPACE/${{env.APP_NAME}}:/workspace/${{env.APP_NAME}}" \
              -w /workspace/${{env.APP_NAME}} \
              ${{matrix.docker_image}} tail -f /dev/null

      - name: Create debian package
        run: |
          docker exec ${{matrix.distro}}-${{matrix.architecture}} sh -c "./CI/setup_and_build.sh ${{matrix.architecture}}" 2>&1

      - name: List build artifacts
        run: |
          docker exec ${{matrix.distro}}-${{matrix.architecture}} ls -la /workspace/

      - name: Copy artifacts
        run: |
          docker cp ${{matrix.distro}}-${{matrix.architecture}}:/workspace/iio-oscilloscope-${{matrix.architecture}}.AppImage ${{github.workspace}}/
          docker exec ${{matrix.distro}}-${{matrix.architecture}} sh -c "mkdir -p /tmp/deb-artifacts && cp /workspace/iio-oscilloscope_* /tmp/deb-artifacts/"
          docker cp ${{matrix.distro}}-${{matrix.architecture}}:/tmp/deb-artifacts/. ${{github.workspace}}/

      - uses: actions/upload-artifact@v7
        with:
          name: osc-linux-${{matrix.architecture}}
          path: |
            ${{github.workspace}}/iio-oscilloscope-${{matrix.architecture}}.AppImage
            ${{github.workspace}}/iio-oscilloscope_*
