on:
  push:
    branches: [master,flatpak]
  pull_request:
name: flatpak build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
      with:
        bundle: iio-oscilloscope.flatpak
        manifest-path: CI/flatpak/app.yml
        cache-key: flatpak-builder-${{ github.sha }}
