on:
  push:
    branches: [ubuntu20.04-v0.14]
name: deb build for Ubuntu 20.04
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update &&
           sudo apt-get install -y
           build-essential cmake git
           libgtk2.0-dev libxml2-dev
           libcurl4-openssl-dev libad9361-dev
           libaio-dev libiio-dev libgtkdatabox-dev
           libjansson-dev libmatio-dev libfftw3-dev

    - name: Generate deb package
      run: mkdir build && cd $_ &&
           cmake -DENABLE_PACKAGING=ON .. && make package

    - name: Upload deb package
      uses: actions/upload-artifact@v3
      with:
        name: iio-oscilloscope-Ubuntu20.04.deb
        path: build/iio-oscilloscope-*-Linux.deb
        if-no-files-found: error
