name: windows-mingw build

on: [push, pull_request]

jobs:

  make-exe-64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Pull the Docker Image
      run: docker pull shooteu/iio-oscilloscope 
      
    - name: Run Docker Image
      shell: cmd
      run: |
            mkdir %GITHUB_WORKSPACE%\artifacts & echo %GITHUB_WORKSPACE%

            set "BUILD_HOST=windows-2019"
            set "USERNAME=github-actions"

            for /F "tokens=1,2 delims=/" %%a in ("%GITHUB_REPOSITORY%") do (
              set "GITHUB_REPO_OWNER=%%a"
              set "GITHUB_REPO_NAME=%%b"
            )

            echo %BUILD_HOST% & echo %USERNAME% & echo %GITHUB_REPO_OWNER% & echo %GITHUB_REPO_NAME%

            docker run ^
                -e BRANCH=%GITHUB_REF_NAME% ^
                shooteu/iio-oscilloscope C:\msys64\usr\bin\bash.exe -c '/home/iio-oscilloscope/docker/inside_docker.sh '
            docker ps - q -l > lastcontainer
            set /p LAST=<lastcontainer
            docker cp %LAST%:C:\msys64\home\docker\iio-oscilloscope\artifact\adi-osc-setup.exe %GITHUB_WORKSPACE%\artifacts

    - uses: actions/upload-artifact@v2
      with:
        name: adi-osc-setup.exe
        path: ${{ github.workspace }}\artifacts\adi-osc-setup.exe
